services:
  mysql:
    image: mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=sgpo_routes
      - MYSQL_ROOT_PASSWORD=admin
